распарсить-запрос-по-n-му-количеству-параметров-плюс-сделай-на-вьюхе-фильтра, регистрация-нового-юзера-от-админа-бросает-исключениецию,
StalnoyKapibar/jobseeker-platform pull request #157
Opened 2019-09-20 08:57 UTC by johnlivingstonseagul

1) https://trello.com/c/FHkDyKFK/121
2) https://trello.com/c/qit8XIEZ/187
Добавлен фильтер на страницу емплоера (все резюме)
добавлены выпадающие подсказки в полях
починено добавление нового юзера со стороны админы

2019-09-20 11:24 UTC, Zemez requested changes
Насчет передачи SQL/HQL запроса из сервиса в DAO это принципиальный вопрос. HTML/JS просмотрел бегло, глубоко в логику особенно не вдавался, внешне все чисто. Много пустых строк, я бы почистил.

2019-09-20 11:24 UTC, Zemez commented on src/main/java/com/jm/jobseekerplatform/controller/rest/CityRestController.java
> +@RequestMapping("api/cities")
Почему не "/api/cities"? Может показаться что это придирка, но я реально не понимаю.

2019-09-20 11:24 UTC, Zemez commented on src/main/java/com/jm/jobseekerplatform/dao/impl/ResumeDAO.java
> +        Query query = entityManager.createQuery(q, Resume.class);
Если это внутренняя реализация, то почему паблик? Если это внешняя, то где интерфейс? Почему принимает строку запроса в параметрах? Кто то из вне должен знать что DAO работает с SQL/HQL запросами или еще чем то?

2019-09-20 11:24 UTC, Zemez commented on src/main/java/com/jm/jobseekerplatform/service/impl/ResumeService.java
> +        return dao.getResumeByFilter(whereQuery.toString(),10,0, whereQueryCount.toString());
Сервис не может и не должен знать что DAO работает с SQL/HQL запросами или что бы то ни было еще.

2019-09-20 13:58 UTC, freegastello commented on src/main/resources/static/css/resume_filter.css
> +    content:"";
без содержимого смысла не имеет

2019-09-23 11:42 UTC, nekromant322 requested changes
Незначительные правки

2019-09-23 11:42 UTC, nekromant322 commented on src/main/java/com/jm/jobseekerplatform/service/impl/ResumeService.java
> +        return dao.getResumeByFilter(map,10,0);
магические константы

2019-09-23 11:42 UTC, nekromant322 commented on src/main/java/com/jm/jobseekerplatform/dao/impl/ResumeDAO.java
> +                    List<Long> tags = (List<Long>)entry.getValue();
пробелы
`whereQuery.append(" AND r.salaryMin >= '" + entry.getValue() + "'");`
`String tagsForQuery = "";`

2019-09-23 11:42 UTC, nekromant322 commented on src/main/java/com/jm/jobseekerplatform/service/impl/ResumeService.java
>      public Page<Resume> getFilterQuery(Map<String, Object> map) {
название метода по смыслу не подходит

2019-09-23 11:42 UTC, nekromant322 commented on src/main/java/com/jm/jobseekerplatform/service/impl/ResumeService.java
> +        return dao.getResumeByFilter(map,10,0);
Не очень понятно почему сервис вызывает метод дао всегда с константными параметрами 10, 0 
Как тогда будет работать пагинация?

2019-09-24 02:25 UTC, fumly commented on src/main/java/com/jm/jobseekerplatform/dao/impl/ResumeDAO.java
> +                    List<Long> tags = (List<Long>)entry.getValue();
String queryCount = "select count(distinct r)  from Resume r "; <-2 пробела после скобки, пробел в конце, после r.

2019-09-24 02:29 UTC, fumly commented on src/main/java/com/jm/jobseekerplatform/dao/impl/ResumeDAO.java
> +                    List<Long> tags = (List<Long>)entry.getValue();
"select count(distinct r)  from Resume r "; <- после скобки стоит 2 пробела. можно убрать пробел после r в конце, либо перед всеми AND убрать пробелы

2019-09-24 02:35 UTC, fumly commented on src/main/resources/static/js/all_resumes.js
>      $('#searchButtons').append('<span class="listTags" id="tagItem-' + id + '"><span style="margin:0 5px 5px 0;" class="badge badge-pill badge-success tagButton" id="searchButton-' + id + '" onclick=
если не трудно, можешь заодно разбить строку? я не знаю, какой монитор был у того, кто это писал, но это чересчур уж длинно

2019-09-24 11:28 UTC, StalnoyKapibar reviewed
Правки кода

2019-09-24 11:28 UTC, StalnoyKapibar commented on src/main/java/com/jm/jobseekerplatform/controller/rest/ResumeRestController.java
> +        return resumeService.getResumeByFilter(map, page, 10);
название метода совершенно непонятное, в нем нет данных по аргументам и по возвращаемому значению

2019-09-24 11:28 UTC, StalnoyKapibar commented on src/main/java/com/jm/jobseekerplatform/dao/impl/ResumeDAO.java
>                      List<Long> tags = (List<Long>)entry.getValue();
пробел после явного приведения

2019-09-24 14:24 UTC, merged